# Generated by Django 5.1.7 on 2025-03-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_complete',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='updeated_at',
            new_name='updated_at',
        ),
    ]
